This code will be used for designating out my gph region.

This is based on my region from LRP. 

In [1]:
#import statements... I think these are all of the relevant ones to what I am doing here. 
import datetime as dt
import numpy as np
import xarray as xr
import pickle

/knight/anaconda_jan21/envs/aug21/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
infile = open("../1959_NAOgph500_2div.p", 'rb') 
gph = pickle.load(infile)
infile.close()

In [3]:
##save year index
year = [i for i in range(1959,2022)] #indicate years for data, needed for opening files

In [4]:
##save lat lon indices
lats = []
lons = []
testfile = xr.open_dataset("../../../../era5/gph/era5_gph_1979.nc")
lats.append(testfile.latitude.values)
lons.append(testfile.longitude.values)

lats = lats[0]
lons = lons[0]

/knight/anaconda_jan21/envs/aug21/lib/python3.8/site-packages/xarray/backends/plugins.py:61: RuntimeWarning: Engine 'rasterio' loading failed:
(numpy 1.24.3 (/nfs/home11/grad/2020/ef935217/.local/lib/python3.8/site-packages), Requirement.parse('numpy<1.23.0,>=1.16.5'), {'scipy'})
  warnings.warn(f"Engine {name!r} loading failed:\n{ex}", RuntimeWarning)


In [5]:
print(lats[40:281])
print(lons[320:681])

[80.   79.75 79.5  79.25 79.   78.75 78.5  78.25 78.   77.75 77.5  77.25
 77.   76.75 76.5  76.25 76.   75.75 75.5  75.25 75.   74.75 74.5  74.25
 74.   73.75 73.5  73.25 73.   72.75 72.5  72.25 72.   71.75 71.5  71.25
 71.   70.75 70.5  70.25 70.   69.75 69.5  69.25 69.   68.75 68.5  68.25
 68.   67.75 67.5  67.25 67.   66.75 66.5  66.25 66.   65.75 65.5  65.25
 65.   64.75 64.5  64.25 64.   63.75 63.5  63.25 63.   62.75 62.5  62.25
 62.   61.75 61.5  61.25 61.   60.75 60.5  60.25 60.   59.75 59.5  59.25
 59.   58.75 58.5  58.25 58.   57.75 57.5  57.25 57.   56.75 56.5  56.25
 56.   55.75 55.5  55.25 55.   54.75 54.5  54.25 54.   53.75 53.5  53.25
 53.   52.75 52.5  52.25 52.   51.75 51.5  51.25 51.   50.75 50.5  50.25
 50.   49.75 49.5  49.25 49.   48.75 48.5  48.25 48.   47.75 47.5  47.25
 47.   46.75 46.5  46.25 46.   45.75 45.5  45.25 45.   44.75 44.5  44.25
 44.   43.75 43.5  43.25 43.   42.75 42.5  42.25 42.   41.75 41.5  41.25
 41.   40.75 40.5  40.25 40.   39.75 39.5  39.25 39

In [6]:
##save day indices
import pandas as pd

s = pd.date_range('2011-11-01', periods=152, freq='D').to_series()
test1 = s.dt.strftime('%m-%d')
times = []
for i in range(len(s)):
    times.append(test1[i])

In [7]:
##create array for gph ... 
g = xr.DataArray(data= gph, dims = ["year","day","lat","lon"],coords = dict(year = year,
                                                                                day = times,
                                                                                lat = lats[40:281],
                                                                                lon = lons[320:681]))
g

<xarray.DataArray (year: 63, day: 152, lat: 241, lon: 361)>
array([[[[5046.34938838, 5045.59123344, 5044.83467125, ...,
          5118.29287717, 5119.80759429, 5120.56415647],
         [5038.01764781, 5037.26108563, 5036.50293068, ...,
          5114.50528797, 5115.26344292, 5116.77816004],
         [5029.6875    , 5028.17278287, 5027.41622069, ...,
          5110.71929154, 5112.23400866, 5112.99216361],
         ...,
         [5884.68558869, 5884.68558869, 5884.68558869, ...,
          5851.36340469, 5852.12155963, 5852.12155963],
         [5883.92743374, 5883.92743374, 5883.92743374, ...,
          5854.39283894, 5854.39283894, 5854.39283894],
         [5882.41271662, 5883.17087156, 5883.17087156, ...,
          5856.66411825, 5856.66411825, 5857.42227319]],

        [[5092.5442788 , 5092.5442788 , 5091.78612385, ...,
          5037.26108563, 5038.01764781, 5038.77580275],
         [5080.42654179, 5080.42654179, 5079.66997961, ...,
          5040.29051988, 5041.04708206, 5041.04708206],
         [5069.06695973, 5068.31039755, 5067.55383537, ...,
          5042.56179918, 5043.31995413, 5043.31995413],
...
         [5858.60251019, 5859.35270133, 5859.35270133, ...,
          5842.86283129, 5842.86283129, 5842.11423293],
         [5859.35270133, 5859.35270133, 5859.35270133, ...,
          5844.36321356, 5844.36321356, 5844.36321356],
         [5859.35270133, 5859.35270133, 5859.35270133, ...,
          5845.86200306, 5845.86200306, 5845.86200306]],

        [[5041.65073904, 5041.65073904, 5042.40093017, ...,
          5266.49942661, 5266.49942661, 5267.24961774],
         [5037.15437054, 5037.15437054, 5037.90296891, ...,
          5270.24719674, 5270.99738787, 5270.99738787],
         [5032.65640928, 5032.65640928, 5033.40660041, ...,
          5273.99496687, 5274.745158  , 5274.745158  ],
         ...,
         [5872.84339959, 5872.84339959, 5873.59359072, ...,
          5840.61544343, 5840.61544343, 5840.61544343],
         [5872.84339959, 5872.84339959, 5873.59359072, ...,
          5840.61544343, 5840.61544343, 5840.61544343],
         [5872.84339959, 5872.84339959, 5873.59359072, ...,
          5840.61544343, 5840.61544343, 5840.61544343]]]])
Coordinates:
  * year     (year) int64 1959 1960 1961 1962 1963 ... 2017 2018 2019 2020 2021
  * day      (day) <U5 '11-01' '11-02' '11-03' ... '03-29' '03-30' '03-31'
  * lat      (lat) float32 80.0 79.75 79.5 79.25 79.0 ... 20.75 20.5 20.25 20.0
  * lon      (lon) float32 -100.0 -99.75 -99.5 -99.25 ... -10.5 -10.25 -10.0

In [8]:
##doesnt need to be divided by 10

In [9]:
#select cap (helsinki 60,25)
g_NAO = g.loc[dict(lat=slice(70,60), lon=slice(-40,-20))]
g_NAO

<xarray.DataArray (year: 63, day: 152, lat: 41, lon: 81)>
array([[[[5013.78376656, 5013.78376656, 5013.78376656, ...,
          5090.27299949, 5092.5442788 , 5094.8155581 ],
         [5008.48305301, 5008.48305301, 5008.48305301, ...,
          5091.02956167, 5093.30084098, 5096.33027523],
         [5002.42418451, 5002.42418451, 5002.42418451, ...,
          5091.78612385, 5094.8155581 , 5097.08843017],
         ...,
         [5144.04147554, 5146.31275484, 5149.34218909, ...,
          5393.95068807, 5394.70884302, 5396.22356014],
         [5160.70177115, 5163.7312054 , 5166.76063965, ...,
          5400.76771152, 5402.28242864, 5403.03899083],
         [5177.36206677, 5179.63493884, 5182.66278033, ...,
          5408.33970438, 5409.85442151, 5410.61257645]],

        [[5061.49496687, 5059.98024975, 5059.2220948 , ...,
          5083.45597604, 5084.97069317, 5086.4854103 ],
         [5060.73681193, 5059.2220948 , 5058.46553262, ...,
          5090.27299949, 5091.78612385, 5093.30084098],
         [5059.98024975, 5059.2220948 , 5057.70737768, ...,
          5097.08843017, 5098.6031473 , 5100.87442661],
...
         [5502.59142457, 5502.59142457, 5503.3416157 , ...,
          5415.6504842 , 5411.90271407, 5408.15494393],
         [5504.09021407, 5504.8404052 , 5504.8404052 , ...,
          5414.90029307, 5411.15252294, 5407.4047528 ],
         [5506.3391947 , 5506.3391947 , 5506.3391947 , ...,
          5414.1516947 , 5410.40392457, 5406.65615443]],

        [[5250.76134047, 5250.76134047, 5250.76134047, ...,
          5309.97069317, 5312.96827217, 5315.2172528 ],
         [5247.76216871, 5247.76216871, 5248.51235984, ...,
          5306.22292304, 5308.47190367, 5311.46948267],
         [5245.51478084, 5245.51478084, 5245.51478084, ...,
          5300.9763634 , 5303.97553517, 5306.97311417],
         ...,
         [5150.32810907, 5154.0758792 , 5157.07345821, ...,
          5364.68367737, 5367.68284913, 5370.68042813],
         [5151.82689857, 5154.82447757, 5157.82364934, ...,
          5367.68284913, 5370.68042813, 5373.67800714],
         [5152.5770897 , 5155.57466871, 5159.32243884, ...,
          5369.18163863, 5372.17921764, 5375.17679664]]]])
Coordinates:
  * year     (year) int64 1959 1960 1961 1962 1963 ... 2017 2018 2019 2020 2021
  * day      (day) <U5 '11-01' '11-02' '11-03' ... '03-29' '03-30' '03-31'
  * lat      (lat) float32 70.0 69.75 69.5 69.25 69.0 ... 60.75 60.5 60.25 60.0
  * lon      (lon) float32 -40.0 -39.75 -39.5 -39.25 ... -20.5 -20.25 -20.0

In [10]:
##pickle out this files
pickle.dump(g_NAO.values, open("1959NAO_gph500.p", 'wb'))

In [11]:
#create weights
weights=np.cos(np.deg2rad(g_NAO.lat))
g_NAO_weight = g_NAO.weighted(weights).mean(dim="lon").mean(dim="lat") #average over the full area
g_NAO_weight

<xarray.DataArray (year: 63, day: 152)>
array([[5111.24645775, 5153.47743452, 5230.57610108, ..., 5471.37380289,
        5499.21142462, 5501.59735672],
       [5239.0929191 , 5271.54077511, 5285.60897115, ..., 5199.77879011,
        5207.40103158, 5260.7564164 ],
       [5260.7564164 , 5299.00273521, 5461.39494374, ..., 5128.50023995,
        5096.53898929, 5218.55853181],
       ...,
       [5400.62998165, 5333.29910738, 5322.41157562, ..., 5661.31711792,
        5689.58847781, 5552.43542372],
       [5148.38257514, 5077.95769016, 5206.18966273, ..., 5279.86662751,
        5510.72028697, 5296.49223663],
       [5296.49223663, 5305.24134341, 5429.85651313, ..., 5485.65221498,
        5470.37362016, 5242.1723111 ]])
Coordinates:
  * year     (year) int64 1959 1960 1961 1962 1963 ... 2017 2018 2019 2020 2021
  * day      (day) <U5 '11-01' '11-02' '11-03' ... '03-29' '03-30' '03-31'

In [12]:
blorp = g_NAO_weight.values

In [13]:
blorp = np.delete(blorp,[120],1)
blorp.shape

(63, 151)

In [14]:
blorp

array([[5111.24645775, 5153.47743452, 5230.57610108, ..., 5471.37380289,
        5499.21142462, 5501.59735672],
       [5239.0929191 , 5271.54077511, 5285.60897115, ..., 5199.77879011,
        5207.40103158, 5260.7564164 ],
       [5260.7564164 , 5299.00273521, 5461.39494374, ..., 5128.50023995,
        5096.53898929, 5218.55853181],
       ...,
       [5400.62998165, 5333.29910738, 5322.41157562, ..., 5661.31711792,
        5689.58847781, 5552.43542372],
       [5148.38257514, 5077.95769016, 5206.18966273, ..., 5279.86662751,
        5510.72028697, 5296.49223663],
       [5296.49223663, 5305.24134341, 5429.85651313, ..., 5485.65221498,
        5470.37362016, 5242.1723111 ]])

In [15]:
pickle.dump(blorp, open("NAO_gph500.p", 'wb'))