### I need to reformat/average the U and GPH profiles. 

May 7th, 2025. 

In [2]:
import numpy as np
import math
import xarray as xr 
import pickle 
import matplotlib.pyplot as plt

In [4]:
infile = open("./large_area_data/1959_gph_2deg.p", 'rb') 
gph = pickle.load(infile)
infile.close()

infile = open("./large_area_data/1959_u_2deg.p", 'rb') 
uwind = pickle.load(infile)
infile.close()

In [5]:
gph.shape

(63, 183, 37, 36, 180)

In [7]:
uwind.shape

(63, 183, 37, 36, 180)

In [8]:
lon = np.arange(0,360,2)

lat = np.arange(90,18,-2)

time = np.arange(0,183,1)

lev = np.array([100., 200., 300., 500., 700., 1000., 2000., 3000., 5000., 7000., 10000., 12500., 15000., 17500., 20000., 22500., 25000., 30000., 35000., 40000., 
                45000., 50000., 55000., 60000., 65000., 70000., 75000., 77500., 80000., 82500., 85000., 87500., 90000., 92500., 95000., 97500., 100000.])

In [9]:
##save year index
year = [i for i in range(1959,2021)] #indicate years for data, needed for opening files

In [11]:
gph = xr.DataArray(data= gph[:62], dims = ["year","day","lev","lat","lon"],coords = dict(year = year,
                                                                                day = time,
                                                                                lev = lev,
                                                                                lat = lat,
                                                                                lon = lon))

uwind = xr.DataArray(data= uwind[:62], dims = ["year","day","lev","lat","lon"],coords = dict(year = year,
                                                                                day = time,
                                                                                lev = lev,
                                                                                lat = lat,
                                                                                lon = lon))

In [12]:
g = gph.sel(lat = slice(75,45))
g

<xarray.DataArray (year: 62, day: 183, lev: 37, lat: 15, lon: 180)>
array([[[[[ 4.64016437e+04,  4.64057085e+04,  4.64104995e+04, ...,
            4.63910041e+04,  4.63946738e+04,  4.63981014e+04],
          [ 4.64925841e+04,  4.64950178e+04,  4.64975917e+04, ...,
            4.64847859e+04,  4.64875255e+04,  4.64900994e+04],
          [ 4.65752421e+04,  4.65786825e+04,  4.65817533e+04, ...,
            4.65691131e+04,  4.65699669e+04,  4.65721075e+04],
          ...,
          [ 4.75001274e+04,  4.75067533e+04,  4.75107288e+04, ...,
            4.75029944e+04,  4.74979613e+04,  4.74959225e+04],
          [ 4.75766692e+04,  4.75825051e+04,  4.75882900e+04, ...,
            4.75857543e+04,  4.75786060e+04,  4.75747452e+04],
          [ 4.76544470e+04,  4.76621305e+04,  4.76712411e+04, ...,
            4.76661570e+04,  4.76579383e+04,  4.76530708e+04]],

         [[ 4.13195209e+04,  4.13229103e+04,  4.13257518e+04, ...,
            4.13096713e+04,  4.13125382e+04,  4.13159276e+04],
          [ 4.13916667e+04,  4.13946356e+04,  4.13973496e+04, ...,
            4.13849643e+04,  4.13864424e+04,  4.13887997e+04],
          [ 4.14670999e+04,  4.14663226e+04,  4.14666539e+04, ...,
            4.14710627e+04,  4.14699159e+04,  4.14684888e+04],
...
          [ 3.90403382e+02,  3.90999075e+02,  3.88781950e+02, ...,
            3.71847699e+02,  3.78479962e+02,  3.85838525e+02],
          [ 3.74048897e+02,  3.76071705e+02,  3.78317500e+02, ...,
            3.48383122e+02,  3.57449126e+02,  3.67932689e+02],
          [ 3.60975502e+02,  3.66709447e+02,  3.76664213e+02, ...,
            3.27903382e+02,  3.37893188e+02,  3.52358657e+02]],

         [[ 2.19262235e+01,  1.31851430e+01,  6.46687079e+00, ...,
            5.80405201e+01,  4.46931705e+01,  3.25021664e+01],
          [ 4.15363152e+01,  3.24511980e+01,  2.43981909e+01, ...,
            7.37069320e+01,  6.20415395e+01,  5.13795874e+01],
          [ 6.70874111e+01,  5.77028545e+01,  4.92038738e+01, ...,
            9.63496435e+01,  8.65573397e+01,  7.68096333e+01],
          ...,
          [ 1.76497446e+02,  1.76424179e+02,  1.73786564e+02, ...,
            1.57878052e+02,  1.64242731e+02,  1.71958073e+02],
          [ 1.56960621e+02,  1.58856008e+02,  1.61748465e+02, ...,
            1.32964061e+02,  1.41297395e+02,  1.51293572e+02],
          [ 1.44269489e+02,  1.50704250e+02,  1.61378944e+02, ...,
            1.11353460e+02,  1.20846324e+02,  1.35330906e+02]]]]])
Coordinates:
  * year     (year) int64 1959 1960 1961 1962 1963 ... 2016 2017 2018 2019 2020
  * day      (day) int64 0 1 2 3 4 5 6 7 8 ... 175 176 177 178 179 180 181 182
  * lev      (lev) float64 100.0 200.0 300.0 500.0 ... 9.5e+04 9.75e+04 1e+05
  * lat      (lat) int64 74 72 70 68 66 64 62 60 58 56 54 52 50 48 46
  * lon      (lon) int64 0 2 4 6 8 10 12 14 ... 344 346 348 350 352 354 356 358

In [13]:
#create weights
g_weights=np.cos(np.deg2rad(g.lat))
zm_g = g.weighted(g_weights).mean(dim="lat")#average over the full area
zm_g ##meridional avg

<xarray.DataArray (year: 62, day: 183, lev: 37, lon: 180)>
array([[[[ 4.71380704e+04,  4.71422891e+04,  4.71472664e+04, ...,
           4.71355825e+04,  4.71342019e+04,  4.71351094e+04],
         [ 4.19633772e+04,  4.19624515e+04,  4.19616605e+04, ...,
           4.19767176e+04,  4.19700619e+04,  4.19657104e+04],
         [ 3.90595804e+04,  3.90542861e+04,  3.90502065e+04, ...,
           3.90811325e+04,  3.90738239e+04,  3.90663901e+04],
         ...,
         [ 6.04366313e+02,  6.14011820e+02,  6.22311929e+02, ...,
           5.80078771e+02,  5.88120395e+02,  5.95452788e+02],
         [ 3.86490598e+02,  3.96663998e+02,  4.05476872e+02, ...,
           3.62764308e+02,  3.70342654e+02,  3.77416375e+02],
         [ 1.73784212e+02,  1.84510907e+02,  1.93721124e+02, ...,
           1.50370937e+02,  1.57591496e+02,  1.64466125e+02]],

        [[ 4.71064835e+04,  4.71139271e+04,  4.71203386e+04, ...,
           4.70995267e+04,  4.70978425e+04,  4.71000355e+04],
         [ 4.19272765e+04,  4.19265434e+04,  4.19265175e+04, ...,
           4.19434711e+04,  4.19376072e+04,  4.19312534e+04],
         [ 3.90271505e+04,  3.90209174e+04,  3.90170903e+04, ...,
           3.90466891e+04,  3.90412125e+04,  3.90347097e+04],
...
         [ 5.90897226e+02,  5.90652963e+02,  5.89831831e+02, ...,
           5.87944528e+02,  5.88465527e+02,  5.89923246e+02],
         [ 3.77126484e+02,  3.76436539e+02,  3.75289963e+02, ...,
           3.75811562e+02,  3.75819549e+02,  3.76707989e+02],
         [ 1.67772369e+02,  1.66683182e+02,  1.65360652e+02, ...,
           1.68446180e+02,  1.67837461e+02,  1.67995863e+02]],

        [[ 4.73302838e+04,  4.73290997e+04,  4.73230083e+04, ...,
           4.73003515e+04,  4.73150554e+04,  4.73251582e+04],
         [ 4.18469373e+04,  4.18582435e+04,  4.18654931e+04, ...,
           4.17986969e+04,  4.18173046e+04,  4.18332487e+04],
         [ 3.87239571e+04,  3.87391375e+04,  3.87538246e+04, ...,
           3.86811200e+04,  3.86941498e+04,  3.87088549e+04],
         ...,
         [ 5.92026397e+02,  5.86739227e+02,  5.80662049e+02, ...,
           5.94316681e+02,  5.94165283e+02,  5.94412109e+02],
         [ 3.80208550e+02,  3.74624210e+02,  3.68256233e+02, ...,
           3.81763531e+02,  3.81886048e+02,  3.82539615e+02],
         [ 1.72846687e+02,  1.66981388e+02,  1.60341826e+02, ...,
           1.74178659e+02,  1.74347803e+02,  1.75187406e+02]]]])
Coordinates:
  * year     (year) int64 1959 1960 1961 1962 1963 ... 2016 2017 2018 2019 2020
  * day      (day) int64 0 1 2 3 4 5 6 7 8 ... 175 176 177 178 179 180 181 182
  * lev      (lev) float64 100.0 200.0 300.0 500.0 ... 9.5e+04 9.75e+04 1e+05
  * lon      (lon) int64 0 2 4 6 8 10 12 14 ... 344 346 348 350 352 354 356 358

In [14]:
#create weights
u_weights=np.cos(np.deg2rad(uwind.lat))
zm_u = uwind.weighted(u_weights).mean(dim="lon")#average over the full area
zm_u ##zonal avg

<xarray.DataArray (year: 62, day: 183, lev: 37, lat: 36)>
array([[[[ 1.51646805e+00,  4.23255963e+00,  8.84156299e+00, ...,
           6.99673606e+00,  1.74055930e+00, -3.82661463e+00],
         [-3.12447977e+00,  4.71204398e+00,  8.76743671e+00, ...,
           7.79431387e+00,  5.71850536e+00,  4.43632218e+00],
         [-3.33858943e+00,  4.59659941e+00,  8.16745725e+00, ...,
           7.06553906e+00,  6.23393912e+00,  6.06336078e+00],
         ...,
         [-5.01960754e-01,  1.76652476e+00,  2.13911455e+00, ...,
          -2.68683489e+00, -2.91138730e+00, -3.09562531e+00],
         [-7.83309937e-02,  1.68747440e+00,  1.66907705e+00, ...,
          -2.50846608e+00, -2.79484439e+00, -2.99998220e+00],
         [ 5.21099091e-01,  1.56434860e+00,  1.38081589e+00, ...,
          -2.27495126e+00, -2.58766963e+00, -2.79748001e+00]],

        [[ 8.55770111e-01,  4.39542940e+00,  9.32635930e+00, ...,
           7.68639077e+00,  2.27568114e+00, -3.38224258e+00],
         [-8.11424255e-02,  4.46229833e+00,  8.12579931e+00, ...,
           9.28973431e+00,  6.96220339e+00,  5.34648887e+00],
         [-5.81624603e+00,  2.94097239e+00,  6.70805410e+00, ...,
           8.32490251e+00,  7.07704281e+00,  6.62888743e+00],
...
         [ 8.59950638e+00,  1.97897144e+00,  3.31395001e+00, ...,
          -2.86153013e+00, -3.40415437e+00, -3.78970532e+00],
         [ 7.19340897e+00,  2.05574078e+00,  3.42657276e+00, ...,
          -2.94656364e+00, -3.35454839e+00, -3.60042241e+00],
         [ 3.43712616e+00,  1.84614037e+00,  2.78587019e+00, ...,
          -2.83296119e+00, -3.21511587e+00, -3.43753611e+00]],

        [[ 7.22208786e+00,  5.00348706e+00,  8.57030835e+00, ...,
           1.54887952e+01,  1.46325940e+01,  1.43293551e+01],
         [ 8.30355453e+00,  2.78180974e+00,  5.12655529e+00, ...,
           1.27602904e+00,  1.01451102e+00,  1.67048433e+00],
         [ 1.22996826e+01,  1.04894206e+00,  1.79634060e+00, ...,
          -4.90977919e+00, -6.75973307e+00, -7.75114746e+00],
         ...,
         [ 7.89931107e+00,  5.44981155e+00,  7.82164179e+00, ...,
          -2.85916468e+00, -3.54429109e+00, -3.93312302e+00],
         [ 6.42938614e+00,  5.81962323e+00,  8.14252633e+00, ...,
          -2.87799505e+00, -3.45774494e+00, -3.68910887e+00],
         [ 3.04565430e+00,  3.98040636e+00,  5.79098579e+00, ...,
          -2.77571615e+00, -3.27972683e+00, -3.45751411e+00]]]])
Coordinates:
  * year     (year) int64 1959 1960 1961 1962 1963 ... 2016 2017 2018 2019 2020
  * day      (day) int64 0 1 2 3 4 5 6 7 8 ... 175 176 177 178 179 180 181 182
  * lev      (lev) float64 100.0 200.0 300.0 500.0 ... 9.5e+04 9.75e+04 1e+05
  * lat      (lat) int64 90 88 86 84 82 80 78 76 74 ... 34 32 30 28 26 24 22 20

In [16]:
pickle.dump(zm_g.values, open("./processed_vertical_data/1959gph.p", 'wb'))
pickle.dump(zm_u.values, open("./processed_vertical_data/1959u.p", 'wb'))