This code will be used for designating out temperature regions. 

In [1]:
#import statements... I think these are all of the relevant ones to what I am doing here. 
import datetime as dt
import numpy as np
import xarray as xr
import pickle

/knight/anaconda_jan21/envs/aug21/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
infile = open("../../REDO_ProcessERA5/FullNH/FullNH_1000_temp_1959_PT1.p", 'rb') 
file1 = pickle.load(infile)
#test = pickle.load(infile)
infile.close()

infile = open("../../REDO_ProcessERA5/FullNH/FullNH_1000_temp_1959_PT2.p", 'rb') 
file2 = pickle.load(infile)
infile.close()

In [3]:
##save year index
year = [i for i in range(1959,2022)] #indicate years for data, needed for opening files

In [4]:
##save lat lon indices
lats = []
lons = []
testfile = xr.open_dataset("../../era5/gph/era5_gph_1979.nc")
lats.append(testfile.latitude.values)
lons.append(testfile.longitude.values)

lats = lats[0]
lons = lons[0]

/knight/anaconda_jan21/envs/aug21/lib/python3.8/site-packages/xarray/backends/plugins.py:61: RuntimeWarning: Engine 'rasterio' loading failed:
(numpy 1.24.3 (/nfs/home11/grad/2020/ef935217/.local/lib/python3.8/site-packages), Requirement.parse('numpy<1.23.0,>=1.16.5'), {'scipy'})
  warnings.warn(f"Engine {name!r} loading failed:\n{ex}", RuntimeWarning)


In [6]:
##save day indices
import pandas as pd

s = pd.date_range('2011-11-01', periods=152, freq='D').to_series()
test1 = s.dt.strftime('%m-%d')
times = []
for i in range(len(s)):
    times.append(test1[i])

In [7]:
temp = np.concatenate((file1,file2), axis=0)
temp.shape

(63, 152, 361, 1440)

In [8]:
##create array for gph ... 
t = xr.DataArray(data= temp, dims = ["year","day","lat","lon"],coords = dict(year = year,
                                                                                day = times,
                                                                                lat = lats,
                                                                                lon = lons))
t

<xarray.DataArray (year: 63, day: 152, lat: 361, lon: 1440)>
array([[[[263.35592651, 263.35592651, 263.35592651, ..., 263.35592651,
          263.35592651, 263.35592651],
         [263.22195435, 263.22399902, 263.22607422, ..., 263.21575928,
          263.21783447, 263.21987915],
         [262.96429443, 262.96636963, 262.97253418, ..., 262.94985962,
          262.95397949, 262.96017456],
         ...,
         [300.29794312, 300.32885742, 300.36801147, ..., 300.11242676,
          300.16809082, 300.22991943],
         [300.25463867, 300.26907349, 300.30618286, ..., 300.11654663,
          300.10211182, 300.16809082],
         [300.17221069, 300.19900513, 300.22991943, ..., 300.09387207,
          300.02172852, 300.06088257]],

        [[255.68183899, 255.68183899, 255.68183899, ..., 255.68183899,
          255.68183899, 255.68183899],
         [255.39326477, 255.39326477, 255.39326477, ..., 255.39532471,
          255.39532471, 255.39326477],
         [255.17889404, 255.17683411, 255.17683411, ..., 255.18095398,
          255.18095398, 255.17889404],
...
         [298.79177856, 298.65863037, 298.52960205, ..., 299.07476807,
          299.08309937, 298.96032715],
         [298.57330322, 298.43389893, 298.34442139, ..., 298.92703247,
          298.91247559, 298.77096558],
         [298.43389893, 298.30072021, 298.25701904, ..., 298.72937012,
          298.69815063, 298.59411621]],

        [[255.24362183, 255.24362183, 255.24362183, ..., 255.24362183,
          255.24362183, 255.24362183],
         [255.92195129, 255.92195129, 255.9198761 , ..., 255.92402649,
          255.92402649, 255.92402649],
         [255.71595764, 255.71388245, 255.71388245, ..., 255.72012329,
          255.71803284, 255.71595764],
         ...,
         [298.8812561 , 298.78555298, 298.73144531, ..., 298.99569702,
          299.01651001, 298.97280884],
         [298.83132935, 298.75640869, 298.70440674, ..., 298.8833313 ,
          298.90414429, 298.8729248 ],
         [298.77514648, 298.72311401, 298.67108154, ..., 298.78555298,
          298.80426025, 298.78137207]]]])
Coordinates:
  * year     (year) int64 1959 1960 1961 1962 1963 ... 2017 2018 2019 2020 2021
  * day      (day) <U5 '11-01' '11-02' '11-03' ... '03-29' '03-30' '03-31'
  * lat      (lat) float32 90.0 89.75 89.5 89.25 89.0 ... 1.0 0.75 0.5 0.25 0.0
  * lon      (lon) float32 -180.0 -179.8 -179.5 -179.2 ... 179.2 179.5 179.8

In [9]:
#select western north central
wnc_t = t.loc[dict(lat=slice(50,42))]
wnc_t 

<xarray.DataArray (year: 63, day: 152, lat: 33, lon: 1440)>
array([[[[281.08282471, 281.02304077, 280.96737671, ..., 281.12609863,
          281.13021851, 281.12405396],
         [281.1817627 , 281.14465332, 281.10549927, ..., 281.21679688,
          281.22503662, 281.2147522 ],
         [281.31161499, 281.27658081, 281.22091675, ..., 281.31781006,
          281.3260498 , 281.33016968],
         ...,
         [282.46179199, 282.56488037, 282.64730835, ..., 282.12582397,
          282.2350769 , 282.35049438],
         [282.56072998, 282.66174316, 282.73184204, ..., 282.20620728,
          282.32165527, 282.44119263],
         [282.63082886, 282.72976685, 282.80603027, ..., 282.30102539,
          282.40820312, 282.51745605]],

        [[278.94116211, 278.97827148, 279.02154541, ..., 278.6835022 ,
          278.78656006, 278.88757324],
         [278.96795654, 278.98031616, 278.98239136, ..., 278.75152588,
          278.80718994, 278.89993286],
         [278.88345337, 278.86901855, 278.86489868, ..., 278.7947998 ,
          278.82366943, 278.86694336],
...
         [279.58016968, 279.54476929, 279.5322876 , ..., 279.677948  ,
          279.64672852, 279.61968994],
         [279.91516113, 279.82568359, 279.79031372, ..., 280.08370972,
          280.06082153, 280.01086426],
         [280.25015259, 280.16900635, 280.14404297, ..., 280.42077637,
          280.3916626 , 280.34378052]],

        [[280.85983276, 281.2093811 , 281.5090332 , ..., 279.81112671,
          280.07122803, 280.45614624],
         [281.39459229, 281.67132568, 281.97717285, ..., 280.33337402,
          280.68713379, 281.072052  ],
         [281.81280518, 282.11450195, 282.51193237, ..., 280.93890381,
          281.25100708, 281.54647827],
         ...,
         [292.38098145, 292.39968872, 292.44546509, ..., 291.94192505,
          292.14584351, 292.3102417 ],
         [292.73678589, 292.76800537, 292.82415771, ..., 292.34558105,
          292.54742432, 292.68267822],
         [293.01766968, 293.06137085, 293.09466553, ..., 292.71182251,
          292.88244629, 292.96981812]]]])
Coordinates:
  * year     (year) int64 1959 1960 1961 1962 1963 ... 2017 2018 2019 2020 2021
  * day      (day) <U5 '11-01' '11-02' '11-03' ... '03-29' '03-30' '03-31'
  * lat      (lat) float32 50.0 49.75 49.5 49.25 49.0 ... 42.75 42.5 42.25 42.0
  * lon      (lon) float32 -180.0 -179.8 -179.5 -179.2 ... 179.2 179.5 179.8

In [10]:
##pickle out these files
pickle.dump(wnc_t.values, open("1959wnc_temp1000.p", 'wb'))

In [11]:
#create weights
weights=np.cos(np.deg2rad(wnc_t.lat))
wnc_t_weight = wnc_t.weighted(weights).mean(dim="lon").mean(dim="lat") #average over the full area
wnc_t_weight

<xarray.DataArray (year: 63, day: 152)>
array([[280.4763678 , 280.91800583, 280.63999608, ..., 277.22033566,
        277.31884793, 277.32065034],
       [281.49482886, 281.13596118, 281.41313551, ..., 279.37608334,
        279.80464408, 281.90754079],
       [281.90754079, 281.37554596, 280.70881976, ..., 280.06054003,
        279.72430424, 280.32221551],
       ...,
       [282.57814362, 282.14664076, 281.75806987, ..., 280.60673656,
        279.91007532, 279.42445151],
       [282.70467849, 282.65133906, 282.91144274, ..., 279.52485027,
        279.33349382, 281.98923519],
       [281.98923519, 281.78773326, 281.35817779, ..., 279.21044155,
        279.56976726, 283.83854165]])
Coordinates:
  * year     (year) int64 1959 1960 1961 1962 1963 ... 2017 2018 2019 2020 2021
  * day      (day) <U5 '11-01' '11-02' '11-03' ... '03-29' '03-30' '03-31'

In [12]:
##calculate daily mean anomaly
##cap
dailymean_wnc = np.mean(wnc_t_weight,axis=0)
anom_wnc = wnc_t_weight - dailymean_wnc
anom_wnc.shape

(63, 152)

In [13]:
anom_wnc

<xarray.DataArray (year: 63, day: 152)>
array([[-0.95450774, -0.37524512, -0.60321717, ..., -1.60799343,
        -1.61959925, -3.53061232],
       [ 0.06395332, -0.15728977,  0.16992226, ...,  0.54775425,
         0.86619689,  1.05627813],
       [ 0.47666526,  0.082295  , -0.53439349, ...,  1.23221095,
         0.78585705, -0.52904715],
       ...,
       [ 1.14726808,  0.85338981,  0.51485662, ...,  1.77840748,
         0.97162814, -1.42681115],
       [ 1.27380295,  1.35808811,  1.66822949, ...,  0.69652119,
         0.39504664,  1.13797253],
       [ 0.55835966,  0.4944823 ,  0.11496454, ...,  0.38211247,
         0.63132008,  2.98727899]])
Coordinates:
  * year     (year) int64 1959 1960 1961 1962 1963 ... 2017 2018 2019 2020 2021
  * day      (day) <U5 '11-01' '11-02' '11-03' ... '03-29' '03-30' '03-31'

In [14]:
pickle.dump(anom_wnc.values, open("1959weightedANOMwnc_temp1000.p", 'wb'))

In [15]:
pickle.dump(lats, open("era5_latindex.p", 'wb'))
pickle.dump(lons, open("era5_lonindex.p", 'wb'))
pickle.dump(times, open("era5_timeindex.p", 'wb'))