### Remove NaN values from ellipse arrays and across... all others

In [1]:
#relevant import statements
import numpy as np
import math
import xarray as xr 
import pickle 
import matplotlib.pyplot as plt

In [4]:
infile = open("./Updated_Diags/two_wind_1959.p", 'rb') 
wind10 = pickle.load(infile)
infile.close()

infile = open("./Updated_Diags/two_size_1959.p", 'rb') 
size10 = pickle.load(infile)
infile.close()

infile = open("./Updated_Diags/two_cenlat_1959.p", 'rb')
cenlat10 = pickle.load(infile)
infile.close()

infile = open("nao_vals.p", 'rb')
nao = pickle.load(infile)
infile.close()

In [5]:
#eddy-heat flux anonym MDTF at 100hPa 
infile = open("./Updated_Diags/1959ZMeddyheatflux.p", 'rb') 
ehf100 = pickle.load(infile)
infile.close()

In [6]:
wind10.shape

(64, 151)

In [7]:
#remove repeat year
wind10 = np.delete(wind10,[20],0)
cenlat10 = np.delete(cenlat10,[20],0)
size10 = np.delete(size10,[20],0)

In [8]:
print(ehf100.shape)

(63, 152)


In [9]:
ehf100 = np.delete(ehf100,[120],1)

In [10]:
wind10.shape

(63, 151)

In [12]:
nao = nao.reshape((63,151))

In [22]:
clt = (cenlat10 - np.nanmean(cenlat10)) / (np.nanstd(cenlat10))
clt

array([[ 0.91526018,  1.06297936,  1.51846233, ..., -1.54688736,
        -2.049085  , -1.07271178],
       [-0.23269387, -0.08926818,  0.02022203, ...,         nan,
                nan,         nan],
       [ 0.79996367,  0.9701372 ,  0.90329749, ...,  0.61817863,
         0.52376235,  0.51825698],
       ...,
       [ 0.98920071,  0.83593951,  0.63165996, ...,  0.4140326 ,
         0.89413115,  0.96502925],
       [ 1.05409221,  1.23176786,  1.40220855, ..., -0.03987087,
        -0.0934532 ,  0.03693249],
       [-0.65333281, -0.67209892, -0.57297422, ..., -2.7368392 ,
        -2.95525421,         nan]])

In [23]:
sz = (size10 - np.nanmean(size10)) / (np.nanstd(size10))
sz

array([[-0.85123337, -0.85491315, -0.87089097, ..., -2.07078121,
        -2.11553401, -1.74557796],
       [-1.13538628, -1.02951636, -0.94965347, ...,         nan,
                nan,         nan],
       [-1.14528437, -1.03952967, -1.04600483, ..., -1.04504298,
        -1.07225088, -1.15060463],
       ...,
       [-0.38009304, -0.27386187, -0.15864759, ..., -1.05079733,
        -1.04234491, -1.0520591 ],
       [-0.68092244, -0.62071435, -0.5277219 , ..., -0.75090506,
        -0.80122577, -0.92456318],
       [-0.80837896, -0.77992737, -0.78434198, ..., -2.47434881,
        -2.48273158,         nan]])

In [24]:
wd = (wind10 - np.nanmin(wind10)) / (np.nanmax(wind10) - np.nanmin(wind10))
wd

array([[0.52742235, 0.54633708, 0.53140104, ..., 0.38105848, 0.37906713,
        0.37315273],
       [0.45706024, 0.46877864, 0.46504039, ...,        nan,        nan,
               nan],
       [0.47975236, 0.49673652, 0.50387939, ..., 0.52283543, 0.51480643,
        0.50979458],
       ...,
       [0.54497417, 0.55324992, 0.56600555, ..., 0.56538653, 0.57164265,
        0.56920457],
       [0.57602831, 0.58118641, 0.58717874, ..., 0.56419368, 0.52495313,
        0.53862825],
       [0.49278477, 0.50539953, 0.49184677, ..., 0.22475956, 0.22930856,
               nan]])

In [25]:
ehf = (ehf100 - np.nanmean(ehf100)) / (np.nanstd(ehf100))
ehf

array([[-1.24861719, -1.39230334, -1.15469636, ...,  0.71961845,
         0.51008848,  0.33515588],
       [-0.71253365, -0.84594929, -0.90041454, ...,  0.05532098,
        -0.24026373, -1.17408766],
       [-1.17408766, -0.9391181 , -0.99979249, ..., -0.71958668,
        -0.73952979, -0.74247132],
       ...,
       [-0.43859642, -0.59456646, -0.4448245 , ..., -0.06403854,
        -0.2657341 , -0.2417402 ],
       [-0.96787452, -1.35361993, -1.57743849, ...,  0.20512176,
         0.26972525, -0.5362395 ],
       [-0.5362395 , -0.57671962, -0.83579517, ...,  3.70992032,
         3.47774495, -0.69357533]])

In [26]:
nao = (nao - np.nanmean(nao)) / (np.nanstd(nao))
nao

array([[ 1.56385674,  1.00188301,  0.76735854, ...,  0.22419104,
        -0.09662073, -0.43734496],
       [-1.00595611, -1.0656935 , -1.09666842, ..., -3.08101152,
        -3.08101152, -3.08101152],
       [-0.55792593, -0.6762944 , -0.67518816, ..., -0.54022597,
        -0.26255785,  0.0394477 ],
       ...,
       [ 0.47980364,  0.33561359, -0.0800538 , ..., -0.26969389,
        -0.22851903, -0.51345778],
       [ 1.08163269,  0.69369964,  0.51023636, ...,  0.75910804,
         0.46971112,  0.37720877],
       [-1.26250619, -1.19413147, -1.10224925, ..., -0.48281521,
        -0.82847188, -3.08101152]])

In [27]:
indices = np.isnan(wd)
for i in range(0,63):
    for j in range(0,151):
        if indices[i,j] != False:
            print(i)
            print(j)
            print("True")
            wd[i,j] = 0
            clt[i,j] = 0
            sz[i,j] = 0
            ehf[i,j] = 0
            nao[i,j] = 0

1
141
True
1
142
True
1
143
True
1
144
True
1
145
True
1
146
True
1
147
True
1
148
True
1
149
True
1
150
True
4
141
True
4
142
True
4
143
True
4
144
True
4
145
True
4
146
True
4
147
True
4
148
True
4
149
True
4
150
True
11
142
True
11
143
True
11
144
True
11
145
True
11
146
True
11
147
True
11
148
True
11
149
True
11
150
True
13
149
True
13
150
True
15
142
True
15
143
True
15
144
True
15
145
True
15
146
True
15
147
True
15
148
True
15
149
True
15
150
True
19
148
True
19
149
True
19
150
True
20
150
True
23
143
True
23
144
True
23
145
True
23
146
True
23
147
True
23
149
True
23
150
True
24
129
True
24
130
True
24
131
True
24
132
True
24
133
True
24
134
True
24
135
True
24
136
True
24
137
True
24
138
True
24
139
True
24
140
True
24
141
True
24
142
True
24
143
True
24
144
True
24
145
True
24
146
True
24
147
True
24
148
True
24
149
True
24
150
True
25
146
True
25
147
True
25
148
True
25
149
True
25
150
True
26
141
True
26
150
True
27
112
True
27
113
True
27
114
True
27
115
True
27
116
True


In [28]:
##export out NaN removed variables
pickle.dump(sz, open("1959size10_NaN.p", 'wb')) 
pickle.dump(clt, open("1959cenlat10_NaN.p", 'wb'))
pickle.dump(ehf, open("1959ehf100_NaN.p", 'wb')) 
pickle.dump(wd, open("1959wind10_NaN.p", 'wb'))
pickle.dump(nao, open("1959nao_NaN.p", 'wb'))